#!/bin/sh

set -e

case "$1" in
	install|upgrade)	
		[ -f /etc/n4d/conf.d/OpenSysClone.json ] && rm /etc/n4d/conf.d/OpenSysClone.json
		[ -f /etc/n4d/conf.d/OpenSysCloneRescue.json ] && rm /etc/n4d/conf.d/OpenSysCloneRescue.json
		[ -f /etc/n4d/conf.d/OpenSysCloneExport.json ] && rm /etc/n4d/conf.d/OpenSysCloneExport.json
	;;

	abort-upgrade|abort-remove|abort-deconfigure)
	;;
	
	*)
		exit 1
	;;
esac


